### ISSUE TITLE
New row

### ISSUE THREAD

**Issue by guilhermemaia93** [iSarCasm/rails_admin_table_field#1]
Hi, it´s possible add new row in edit table?

**Comment by iSarCasm** [comment]
@guilhermemaia93 Hi, didnt realise somebody would find it :) Yes, I just realise the patch for this is actually outside of this `gem`. It requires to change some of the RailsAdmin JS.

In short. This will work if you add this workaround to `app/assets/javascripts/rails_admin/custom/ui.js`
```js
$(document).ready(function() {
  // Table view ADD button hack
  var oldNestedFormEvents = window.nestedFormEvents.insertFields
  window.nestedFormEvents.insertFields = function (content, assoc, link) {
    var insertable = $(link).parent().siblings('#tab_logic').find('.js-insertable');
    if (insertable.length > 0) {
      insertable.first().append(content);
      return insertable.first().children().last();
    } else {
      return oldNestedFormEvents(content, assoc, link);
    }
  }
});
```

**Comment by iSarCasm** [comment]
@guilhermemaia93 made an update for this (0.1.2).
Inside `app/assets/javascripts/rails_admin/custom/ui.js` add:
`//= require table-field`
